# Generated by Django 5.2.8 on 2025-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Animal Shelter', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Shelter Settings',
                'verbose_name_plural': 'Shelter Settings',
            },
        ),
    ]
