# Generated by Django 5.2.8 on 2025-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_sheltersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheltersettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sheltersettings',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='sheltersettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sheltersettings',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='sheltersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sheltersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sheltersettings',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sheltersettings',
            name='name',
            field=models.CharField(default='My Animal Shelter', max_length=200),
        ),
    ]
